name: Run pwd Command

on:
  push:
    branches:
      - main

jobs:
  run-pwd-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run pwd command
      run: pwd
